border: 100 # Voucher spadnie w losowych koordynatach miedzy -100 a 100
voucherInfo: # Informacja, która jest wysyłana do każdego gracza na serwerze podczas dropu
  - ' '
  - '&c&lDROP VOUCHERA!'
  - ' '
  - '&7Nazwa: {name}'
  - ' '
  - '&7Koordynaty: '
  - ' &aSwiat: &6{world}'
  - ' &aX: &6{x}'
  - ' &aY: &6{y}'
  - ' &aZ: &6{z}'
  - ' '
voucherUseInfo: # Informacja, która jest wysyłana do każdego gracza na serwerze podczas użycia vouchera
  - ' '
  - '&7Gracz &6{player} &7uzyl vouchera &a{name}'
  - ' &a&lGRATULACJE!'
  - ' '
vouchers: # Lista voucherów
  '1':
    delay: 30
    command: 'give {player} diamond 1'
    world: 'world'
    item:
      type: 'paper'
      amount: 1
      name: '&cVoucher #1'
      lore:
        - ' '
        - '&7Kliknij &aPPM &7aby go uzyc'
        - ' '
      enchants:
        - 'durability:10'
  '2':
    delay: 60
    command: 'give {player} emerald 1'
    world: 'world'
    item:
      type: 'paper'
      amount: 1
      name: '&cVoucher #2'
      lore:
        - ' '
        - '&7Kliknij &aPPM &7aby go uzyc'
        - ' '
      enchants:
        - 'durability:20'